
 export const font_list = {
  "Amazon-Ember-Bold": "Amazon-Ember Bold",
  "Amazon-Ember": "Amazon-Ember Regular",
  "OpenSans-Bold": "OpenSans Bold",
  "Proxima-Nova-Black": "Proxima-Nova Black",
  "Proxima-Nova-Bold": "Proxima-Nova Bold",
  "Proxima-Nova-Extrabld": "Proxima-Nova Extra Bold",
  "Proxima-Nova-Regular-It": "Proxima-Nova Regular Italic",
  "Proxima-Nova-Semibold": "Proxima-Nova Semi Bold",
  "Avenir-Next-Bold": "Avenir Next Bold",
  "Avenir-Next-Medium": "Avenir Next Medium",
  "Avenir-Black": "Avenir Black",
  "Century-Gothic": "Gothic",
  "Century-Gothic-Bold": "Gothic Bold",
  "NotoSansSC-Regular": "Noto Sans SC Regular",
  "PlexesPro-Medium": "PlexesPro Medium",
  "PlexesPro-Light": "PlexesPro Light",
  "PlexesPro-Book": "PlexesPro Book",
  "PlexesPro-Black": "PlexesPro Black",
  "Larsseit": "Larsseit Regular",
  "Larsseit-Bold": "Larsseit Bold",
  "Gotham-Black": "Gotham Black",
  "Gotham-Bold": "Gotham Bold",
  "Gotham-Book": "Gotham Book",
  "Gotham-Light": "Gotham Light",
  "Gotham-Medium": "Gotham Medium",
  "Gotham-Thin": "Gotham Thin",
  "Gotham-XLight": "Gotham XLight",
  "Bogle-Regular": "Bogle Regular",
  "Bogle-Bold": "Bogle Bold",
  "National-2": "National2 Regular",
  "National-2-Bold": "National2 Bold",
  "NeueEinstellung-Medium": "NeueEinstellung Medium",
  "Neue-Einstellung-Bold": "NeueEinstellung Bold",
  "Avenir-Next-Condensed-Bold": "AvenirNextCondensed Bold",
  "Avenir-Next-Condensed-Demi-Bold": "AvenirNextCondensed DemiBold",
  "Avenir-Next-Condensed-Heavy": "AvenirNextCondensed Heavy",
  "Avenir-Next-Condensed-Medium": "AvenirNextCondensed Medium",
  "Avenir-Next-Condensed-Regular": "AvenirNextCondensed Regular",
  "Avenir-Next-Condensed-Ultra-Light": "AvenirNextCondensed UltraLight",
  "Avenir-Next-Demi-Bold": "AvenirNext DemiBold",
  "Avenir-Heavy": "Avenir Heavy",
  "Trade-Gothic-LT-Bold": "Trade Gothic LT Bold",
  "Trade-Gothic-LT-Std-Bold-Cn": "TradeGothicLTStd-BdCn20",
  "Trade-Gothic-LT": "Trade Gothic LT",
  "Trade-Gothic-LT-Light": "Trade Gothic LT Light",
  "Trade-Gothic-LT-Std-Cn": "TradeGothicLTStd-Cn18",
  "TESCO-Modern": "TESCO Modern",
  "TESCO-Modern-Bold": "TESCO Modern Bold",
  "Arial": "Arial",
  "Arial-Bold": "Arial-Bold",
  "AlternateGothicATF-Black": "AlternateGothicATF-Black",
  "AlternateGothicATF-Bold": "AlternateGothicATF-Bold",
  "AlternateGothicATF-Heavy": "AlternateGothicATF-Heavy",
  "AlternateGothicATF-Medium": "AlternateGothicATF-Medium",
  "HP-Simplified": "HP-Simplified",
  "HP-Simplified-Bold": "HP-Simplified-Bold",
  "HP-Simplified-Bold-Italic": "HP-Simplified-Bold-Italic",
  "HP-Simplified-Italic": "HP-Simplified-Italic",
  "BarlowCondensed-Black": "BarlowCondensed Black",
  "BarlowCondensed-BlackItalic": "BarlowCondensed Black Italic",
  "BarlowCondensed-Bold": "BarlowCondensed Bold",
  "BarlowCondensed-BoldItalic": "BarlowCondensed BoldItalic",
  "BarlowCondensed-ExtraBold": "BarlowCondensed ExtraBold",
  "BarlowCondensed-ExtraBoldItalic": "BarlowCondensed ExtraBold Italic",
  "BarlowCondensed-ExtraLight": "BarlowCondensed ExtraLight",
  "BarlowCondensed-ExtraLightItalic":
  "BarlowCondensed ExtraLight Italic",
  "BarlowCondensed-Italic": "BarlowCondensed Italic",
  "BarlowCondensed-Light": "BarlowCondensed Light",
  "BarlowCondensed-LightItalic": "BarlowCondensed Light Italic",
  "BarlowCondensed-Medium": "BarlowCondensed Medium",
  "BarlowCondensed-MediumItalic": "BarlowCondensed Medium Italic",
  "BarlowCondensed-Regular": "BarlowCondensed Regular",
  "BarlowCondensed-SemiBold": "BarlowCondensed SemiBold",
  "BarlowCondensed-SemiBoldItalic": "BarlowCondensed SemiBold Italic",
  "BarlowCondensed-Thin": "BarlowCondensed Thin",
  "BarlowCondensed-ThinItalic": "BarlowCondensed Thin Italic",
  "Colfax-Bold": "Colfax Bold",
  "Colfax-Medium": "Colfax Medium",
  "Colfax-Regular": "Colfax Regular",
  "Futura-Bold": "Futura Bold",
  "Futura-Condensed-Medium": "Futura Condensed Medium",
  "Futura-Extra-Bold": "Futura Extra Bold",
  "Futura-Medium": "Futura Medium",
  "Helvetica-Neue-55-Roman": "Helvetica Neue 55 Roman",
  "Helvetica-Neue-65-Medium": "Helvetica Neue 65 Medium",
  "Knockout-Regular": "Knockout Regular",
  "Netto-OT-Bold": "Netto OT Bold",
  "Playfair-Display-Black-Italic": "Playfair Display Black Italic",
  "Playfair-Display-Black": "Playfair Display Black",
  "SourceSansVariable-Roman": "SourceSansVariable Roman",
  "SourceSansVariable-Bold": "SourceSansVariable Bold"
};
