<?php

return [
    'AmazonFresh_1H+1S_1H_Left' => 324,
    'AmazonFresh_1H+1S_1H_Top' => 111,
    'AmazonFresh_1H+1S_1H_FontSize' => 50,
    'AmazonFresh_1H+1S_1H_FontFamily' => 'Amazon-Ember-Bold',
    'AmazonFresh_1H+1S_1S_Left' => 324,
    'AmazonFresh_1H+1S_1S_Top' => 163,
    'AmazonFresh_1H+1S_1S_FontSize' => 36,
    'AmazonFresh_1H+1S_1S_FontFamily' => 'Amazon-Ember',

    'AmazonFresh_NEW+1H_NEW_Left' => 324,
    'AmazonFresh_NEW+1H_NEW_Top' => 110,
    'AmazonFresh_NEW+1H_NEW_FontSize' => 36,
    'AmazonFresh_NEW+1H_NEW_FontFamily' => 'Amazon-Ember',
    'AmazonFresh_NEW+1H_1H_Left' => 324,
    'AmazonFresh_NEW+1H_1H_Top' => 155,
    'AmazonFresh_NEW+1H_1H_FontSize' => 50,
    'AmazonFresh_NEW+1H_1H_FontFamily' => 'Amazon-Ember-Bold',

    'AmazonFresh_2H_1H_Left' => 326,
    'AmazonFresh_2H_1H_Top' => 105,
    'AmazonFresh_2H_1H_FontSize' => 50,
    'AmazonFresh_2H_1H_FontFamily' => 'Amazon-Ember-Bold',
    'AmazonFresh_2H_2H_Left' => 326,
    'AmazonFresh_2H_2H_Top' => 160,
    'AmazonFresh_2H_2H_FontSize' => 50,
    'AmazonFresh_2H_2H_FontFamily' => 'Amazon-Ember-Bold',

    'AmazonFresh_2H+1S_1H_Left' => 326,
    'AmazonFresh_2H+1S_1H_Top' => 84,
    'AmazonFresh_2H+1S_1H_FontSize' => 50,
    'AmazonFresh_2H+1S_1H_FontFamily' => 'Amazon-Ember-Bold',
    'AmazonFresh_2H+1S_2H_Left' => 326,
    'AmazonFresh_2H+1S_2H_Top' => 139,
    'AmazonFresh_2H+1S_2H_FontSize' => 50,
    'AmazonFresh_2H+1S_2H_FontFamily' => 'Amazon-Ember-Bold',
    'AmazonFresh_2H+1S_1S_Left' => 326,
    'AmazonFresh_2H+1S_1S_Top' => 191,
    'AmazonFresh_2H+1S_1S_FontSize' => 36,
    'AmazonFresh_2H+1S_1S_FontFamily' => 'Amazon-Ember',

    'AmazonFresh_1H+2S_1H_Left' => 326,
    'AmazonFresh_1H+2S_1H_Top' => 91,
    'AmazonFresh_1H+2S_1H_FontSize' => 50,
    'AmazonFresh_1H+2S_1H_FontFamily' => 'Amazon-Ember-Bold',
    'AmazonFresh_1H+2S_1S_Left' => 326,
    'AmazonFresh_1H+2S_1S_Top' => 143,
    'AmazonFresh_1H+2S_1S_FontSize' => 36,
    'AmazonFresh_1H+2S_1S_FontFamily' => 'Amazon-Ember',
    'AmazonFresh_1H+2S_2S_Left' => 326,
    'AmazonFresh_1H+2S_2S_Top' => 185,
    'AmazonFresh_1H+2S_2S_FontSize' => 36,
    'AmazonFresh_1H+2S_2S_FontFamily' => 'Amazon-Ember',

    'AmazonFresh_3H_1H_Left' => 326,
    'AmazonFresh_3H_1H_Top' => 73,
    'AmazonFresh_3H_1H_FontSize' => 50,
    'AmazonFresh_3H_1H_FontFamily' => 'Amazon-Ember-Bold',
    'AmazonFresh_3H_2H_Left' => 326,
    'AmazonFresh_3H_2H_Top' => 128,
    'AmazonFresh_3H_2H_FontSize' => 50,
    'AmazonFresh_3H_2H_FontFamily' => 'Amazon-Ember-Bold',
    'AmazonFresh_3H_3H_Left' => 326,
    'AmazonFresh_3H_3H_Top' => 183,
    'AmazonFresh_3H_3H_FontSize' => 50,
    'AmazonFresh_3H_3H_FontFamily' => 'Amazon-Ember-Bold',

    'DropShadow_Radius' => 12,
    'DropShadow_Color' => '#59000000',
    'DropShadow_X' => 30,
    'DropShadow_Y' => 30,
    'AmazonFresh_Products_Top' => 14,
    'AmazonFresh_Products_Left' => 700,
    'AmazonFresh_Products_Bottom' => 300,
    'AmazonFresh_Products_Right' => 1200, 
    'pil_font' => "off",
    'Show_3H' => "off",
    'Show_Text_Tracking' => "off", 
    'Notification_Emails' => '',

    'sftp_address' => '', 
    'sftp_port' => '', 
    'sftp_dir_path' => '', 
    'sftp_username' => '', 
    'sftp_password' => '', 
    'scheduled_days_of_week' => '1', 
    'scheduled_time' => '13:00', 
    'scheduled_product_image' => 'on',
    'scheduled_nf_image' => 'off',
    'scheduled_ingredient_image' => 'off',
    'scheduled_import_file_type' => '0', 
    'scheduled_column_url' => 'Image URL', 
    'scheduled_column_name' => 'GTIN',

    'onetime_import_image_type' => '0',
    'onetime_product_image' => 'on', 
    'onetime_nf_image' => 'off', 
    'onetime_ingredient_image' => 'off'
];